language: ruby

rvm: 2.2.0

addons:
  browserstack:
    username: "ashwingonsalves2"
    access_key:
      secure: "H74HuM9O1cNmVVCs9WJDF9U/iwQ1wmJSW2Iw7/WmwnxLedchhPPUbABjgbSnQhLRolKdNYq3MrvPxFhxt140hHjfJuXovzQeqSO7Rl+I4sNATpe6FSmwo3Eh0Iq9MW6f4lHnX5ukGyJYelaKW2iNwAvP+4tmaHQXF0R3W1aPIRblOS4v1rx1R6e8GlW7UDmmYfcjRKNiutTCVRxLTBRz8ud/gweoM8VtffV2V6iLizybgMcHHZ7MPNOqwaZNj4cpFVonooHe8OhUZrNmGSM3Q0udpGAB9XjcyfbFhjIxUpEgYBbsLJGBpQrF6DfYejAupv7eMD5JFvtgUWrwYhV5bkGxcorH0RCkDO6dz+VqxrXyEk6lvwfZzSgyRgB/jh3k6R0W5OT3FjIzhjJ4r7kdNbxDpdL95UInWTO0EsgqGlx+amkIdj6iw3f2eQzVXq3s1TEmfP8iXKX7oKvWt1nIuRr2OtOQxrg4PNl9IA5v3gIQTxSh35nqergxeWsQ2HeCo8KrpSymiK12pY1ms5XC4Q3Tpj5Q3n3tTucd5A5ABnsviVK6vSyxhXRX39on9lzFwxsbDikg5yoNLSRwfa0VFLBbEQARRQzVSOdmJcWL5rtI6Cq0vqMVBfzEY69KD+9WxyDxasyrf78ktH5cDKEnGFGOa6IszBl3S1qsgNTZt38="

env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"

before_script:
  - gem install selenium-webdriver

script:
  - ruby sample_test.rb

