language: ruby

rvm: 2.2.0

addons:
  browserstack:
    username: "ashwingonsalves2"
    access_key:
      secure: "EpD2DT09CTw4xDqGjVNi4AAbf9rRYwoHjC4SS4q/8sDAPN2OC7Pp8qTmVZS+bSyhgH7ApI90ayLg1HSCXFR9jmO9aYIe90RUV73hFMx1RZOT+o4BuC7QzKBTBHL+L4Sjh4rRNHUrTI/pBjWmThvuvLnkDjepIYgRB8bi0SmUSGGddBU94yQtvsHtnrFpUxamcQ6V1HYZVaU/y9QrLaLlFFT1Uei5XKjAs/vQ1V7/ZLXouJdciQHkG0Ug8p543hhCpS42J7cWU5bnB7aNHM6rG/3VcM8jrgFqrPivBCI7GIJB7Nm7qBI9qSQatZ1Bdobi/hTjlQ7Qf8EOYfakHDW2J7qLjXtI2Utfrf0PYShoxBlila59mRUDIqWjgEBfhzq1x+/AHeyvZGdBPigTadbvpG6x/On8S/DNwBv2ovONowfweqTx93lbak+Y2Bvvwjsq280jLys6NB/28XWGSkz5TqRIxb30No9wXwccYGqcFZAiHcPxxp4vX0g6/sIQTZdixWNj2lL/LFf4WShoRwum0PMo1vBBjUTSLIGXGAFrI51YOasvOOGvH9gBvVA62rJsNKNDjwc+BVSaLNMpFd9a9pWxsunKhR6XAo4fi88nbS9IGPegm0185VNV4SNXeu5ztsv1Fq0GyX+YQVAsGmkXxUEJpVtyb4sG7gSBqcEF0QM="

env:
  global:
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"

before_script:
  - gem install selenium-webdriver

script:
  - ruby sample_test.rb

